[package]
name = "type_hierarchy"
version = "0.1.0"
edition = "2024"

[dependencies]
scope = { path = "../scope" }
syntax = { path = "../syntax" }
scanner = { path = "../scanner" }
synonym = "0.1.6"
bidirectional-map = "0.1.4"
